wandb_version: 1

n_env_horizon:
  desc: null
  value: 100
update_iteration:
  desc: null
  value: 5000
total_step:
  desc: null
  value: 100000000
randomness:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    code_path: code/main/train_imitate_dexmv.py
    python_version: 3.8.19
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723498956
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 3
      - 13
      - 15
      - 16
      - 22
      - 23
      - 61
      4: 3.8.19
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''activation_fn'': <class ''torch.nn.modules.activation.ReLU''>}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 100000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: 100
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1723498962048658717
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: None
_last_obs:
  desc: null
  value: "[[-3.14159282e-02  1.34390354e-01  3.14159282e-02  2.39110112e-01\n   3.14159274e+00\
    \  1.46433127e+00 -3.49066011e-03  0.00000000e+00\n   0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00 -3.14159282e-02\
    \  1.34390354e-01\n   3.14159282e-02  2.39110112e-01  3.14159274e+00  1.46433127e+00\n\
    \  -3.49066011e-03  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n\
    \   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00\n   0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00  0.00000000e+00\n  -1.25040114e-03  2.30392516e-02\
    \  9.01000023e-01  6.46210909e-01\n  -2.91396797e-01 -6.42854989e-01  2.90236264e-01\
    \  0.00000000e+00\n  -2.88706124e-01 -1.37397036e-01 -2.00111151e-01 -3.68299484e-01\n\
    \  -4.24652696e-02 -2.29232550e-01 -3.92887771e-01 -3.91028970e-02\n  -2.31607676e-01\
    \ -4.18146312e-01 -4.16100323e-02 -2.30482697e-01\n  -4.38351572e-01 -4.76293862e-02\
    \ -2.27197409e-01  2.85378635e-01\n  -1.37335002e-01 -2.00275779e-01  3.65066469e-01\
    \ -4.24469635e-02\n  -2.29280949e-01  3.89660060e-01 -3.90981026e-02 -2.31620431e-01\n\
    \   4.14915502e-01 -4.16191220e-02 -2.30458617e-01  4.35112655e-01\n  -4.76495624e-02\
    \ -2.27144003e-01  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00  0.00000000e+00\n   0.00000000e+00  0.00000000e+00  0.00000000e+00\
    \  0.00000000e+00]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at
    0x7fd961ca8970>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (116,), float32)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (32,), float32)
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 20000
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 2000
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x7fd9431da670>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: 0.2
kl_scheduler:
  desc: null
  value: <stable_baselines3.ppo.ppo.AdaptiveScheduler object at 0x7fd9a63dd7c0>
lr_schedule:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x7fd9a62c6790>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7fd9a6342dc0>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=116,\
    \ out_features=64, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): ReLU()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=116, out_features=64, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): ReLU()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=32, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7fd9a62bf880>
